version: '3.8'
services:
  backend:
    build:
      context: ./Backend
    ports:
      - "7000:7000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/image_moderation
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data: